### ISSUE TITLE
Interested in a pull request for previewing SwiftUI?

### ISSUE THREAD

**Issue by xenodium** [zweifisch/ob-swift#4]
Wrote a snippet patching _org-babel-execute:swift_ to preview SwiftUI blocks. Interested in including in ob-swift? Happy to send PR.

Wrote about it here http://xenodium.com/swiftui-layout-previews-using-emacs-org-blocks

![ob-swiftui](https://user-images.githubusercontent.com/8107219/82758541-0bd50880-9ddf-11ea-9692-5d984dc9919f.gif)

**Comment by scott56gps** [comment]
I'm interested!  This looks very helpful.  Great job @xenodium

**Comment by xenodium** [comment]
> I'm interested!

Nice. @scott56gps we may want to consider a separate package (maybe ob-swiftui). ob-swift seems a little inactive. Goals are likely different enough for separate packages anyway.

**Comment by scott56gps** [comment]
I agree that a separate package would be appropriate.  By the way, I ran the swiftui code yesterday and it works great!

**Comment by xenodium** [comment]
> By the way, I ran the swiftui code yesterday and it works great!

Ah nice to hear @scott56gps! Gave me a good nudge to give it a go...  see if ob-swiftui works for ya. I'm sure it'll need changes but it's a start.

https://github.com/xenodium/ob-swiftui

**Comment by xenodium** [comment]
ps. It also supports multiple view structs now.

```
#+begin_src swiftui :results window :view FooView
  struct FooView: View {
    var body: some View {
      VStack(spacing: 10) {
        BarView()
        BazView()
      }
    }
  }

  struct BarView: View {
    var body: some View {
      Rectangle()
        .fill(Color.yellow)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
  }

  struct BazView: View {
    var body: some View {
      Rectangle()
        .fill(Color.blue)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
  }
#+end_src
```

**Comment by scott56gps** [comment]
@xenodium, I just installed the updated ob-swiftui.el and it works great!  Thank you for providing this functionality.

**Comment by xenodium** [comment]
Thanks @scott56gps. Great to hear!

**Comment by konrad1977** [comment]
Can this be used somehow as a minor mode to preview SwiftUI in Emacs? I mean outside org-mode. Like a side by side buffer ala Xcode? How can we preview more complex views with dependencies that lives outside the view?

**Comment by xenodium** [comment]
> Can this be used somehow as a minor mode to preview SwiftUI in Emacs?

As is, no. But the logic could be moved/extended. Needs work.
